const STORAGE_ACCESS_TOKEN_NAME: string = 'access_token';
const STORAGE_REFRESH_TOKEN_NAME: string = 'refresh_token';

const STORAGE_BASKET_PRODUCTS_NAME: string = 'STORAGE_BASKET_PRODUCTS_NAME';
const STORAGE_BASKET_RETAIL_POINT: string = 'STORAGE_BASKET_RETAIL_POINT';

const ARRAY_SUCCES_STATUS_CODES: number[] = [200, 201];

export {
  STORAGE_ACCESS_TOKEN_NAME,
  STORAGE_REFRESH_TOKEN_NAME,
  ARRAY_SUCCES_STATUS_CODES,
  STORAGE_BASKET_PRODUCTS_NAME,
  STORAGE_BASKET_RETAIL_POINT,
};
