const MODAL_LOGIN_IN_MAINPAGE: string = 'MODAL_LOGIN_IN_MAINPAGE';
const MODAL_SIGNUP_IN_MAINPAGE: string = 'MODAL_SIGNUP_IN_MAINPAGE';
const MODAL_RESET_PASSWORD_IN_MAINPAGE: string =
  'MODAL_RESET_PASSWORD_IN_MAINPAGE';
const MODAL_CHANGE_PASSWORD_IN_MAINPAGE: string =
  'MODAL_CHANGE_PASSWORD_IN_MAINPAGE';
const MODAL_SIGNUP_SUCCESS: string = 'MODAL_SIGNUP_SUCCESS';
const MODAL_CONFIRM_EMAIL_SUCCESS: string = 'MODAL_CONFIRM_EMAIL_SUCCESS';

export {
  MODAL_LOGIN_IN_MAINPAGE,
  MODAL_SIGNUP_IN_MAINPAGE,
  MODAL_CHANGE_PASSWORD_IN_MAINPAGE,
  MODAL_RESET_PASSWORD_IN_MAINPAGE,
  MODAL_SIGNUP_SUCCESS,
  MODAL_CONFIRM_EMAIL_SUCCESS,
};
